### ISSUE TITLE
[Question] How to make the header sticky?

### ISSUE THREAD

**Issue by taquangtrung** [daviddarnes/alembic#138]
Hi,

I'm using your Alembic theme and really love it.

I'd like to ask if it is possible to make the header sticky in your Alembic template?

I saw that the header that Alembic used is not stored in the `<head/>` section but in a section `<header/>` of the `<body/>`. 

Hence, all solutions that I tried online like below don't work

https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
https://www.w3schools.com/howto/howto_js_sticky_header.asp

Thank you!

**Comment by daviddarnes** [comment]
That's going to require a bit of dev work. Here's what I'd do:
1. Move the feature out of the header component so it sits above the main content area
2. Add the following CSS:
  ``` css
  .header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background: white;
  }
  ```

Let us know how it goes. Going to close this as it's not a bug, but happy to chat this through ✨
