### ISSUE TITLE
[Question]: Show Tables ?

### ISSUE THREAD

**Issue by fjolublar** [daviddarnes/alembic#170]
Working with md files you can create table like:

| Col_Name_1 | Col_Name_2 |
| --------------|:--------------:|
| Value_1        |     Value_2    |

Trying this in a post doesn't show the table (lines of the table). It just does the sorting.

Any help on how to show also the table?

**Comment by daviddarnes** [comment]
Looks like my theme is missing some table styles! I think this is the first time it's been requested though. For now you could add some styles to add a background to the heading row and every other row to help with readability. Here's some example code:

```css
thead tr,
tr:nth-of-type(2) {
  background: rgba(0, 0, 0, 0.1);
}
```
