### ISSUE TITLE
Re: Custom Properties Settings

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/alembic#51]
Following code is to style the colour inputs, however they aren't needed in the main theme:
``` css

input[type="color"] {
  padding: 0;
  height: 2.4rem;
  &::-webkit-color-swatch-wrapper {
  	padding: 0;
    &:after {
      content: "Color";
    }
  }
  &::-webkit-color-swatch {
  	border: none;
  }
}
```
Best to just add them to the styling page and not the main codebase
