### ISSUE TITLE
Scroll bars for Code Snippet

### ISSUE THREAD

**Issue by BasanthVerma** [daviddarnes/alembic#60]
Hi David, Thank you for the awesome theme (And thanking all those who contributed)!

I am setting up Alembic to my blog site from scratch and I'm facing an issue where I don't see scroll-bars for code snippets. I also installed kramdown rouge and I have set the following properties in my _config.yml:

```
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
```

But I still couldn't get the scroll bars for the code-snippets -- lengthy lines are wrapping into the next line. Here is how it looks:

![screen shot 2017-08-31 at 7 39 45 pm](https://user-images.githubusercontent.com/8429864/29927622-85e06c40-8e84-11e7-9fc7-b4b991eea1d1.png)

Please guide me on how I can get the scroll-bars there. Thank you!

**Comment by daviddarnes** [comment]
Thanks @BasanthVerma, so glad you like it! I'll put in a fix now for this, however if you need a quick patch you can use the following css:
``` css
.typeset pre {
    white-space: pre;
    overflow: scroll;
}
```
