### ISSUE TITLE
Twitter card blank

### ISSUE THREAD

**Issue by SimonEnsemble** [daviddarnes/alembic#78]
A Twitter card when sharing a post does not display an image, e.g.:

https://twitter.com/CoryMSimon/status/947217511174496256

What is the best way to e.g. use the site logo as an image for a Twitter card in the Alembic theme?

Also, the Twitter share button, when clicked on the post, does not include the link to the post.

Thanks, awesome theme!

**Comment by daviddarnes** [comment]
@SimonEnsemble how strange. I just checked the metadata and noticed that your `og:image`url is over `http` but the site is over `https`. Can you change it?

**Comment by SimonEnsemble** [comment]
How do I do that? Upon `grep -r "og:image"`, I do not see a line where I can change the `og:image`, except in the `_site` directory, which to my understanding is the build. I wonder where the `og:image` is being pulled from.

I did `grep -r og:` to find `_layouts/default.html` to contain `og:title` and `og:description`, so I added the following line:
```
<meta property="og:image" content="images/treez.jpg">
```
but that did not fix it.

**Comment by SimonEnsemble** [comment]
I tried changing the `url: ` line in `_config.yml` to be https instead of http as well, if that's what you were intending. See [here](https://github.com/SimonEnsemble/SimonEnsemble.github.io/blob/master/_config.yml/#L89).

**Comment by daviddarnes** [comment]
@SimonEnsemble you can set an `image` option in the frontmatter of any post or page, for example:
```
image: /assets/some-kind-of-image.jpg
```
You can also replace `assets/default-social-image.png` which will appear for all posts

**Comment by daviddarnes** [comment]
@SimonEnsemble hey did you solve this?

**Comment by SimonEnsemble** [comment]
Sorry, I should know more... In which file should I put:

```
<meta name="twitter:card" content="summary_large_image">
```
in your theme?

I put up a default-social-image here:
https://github.com/SimonEnsemble/SimonEnsemble.github.io/blob/master/assets/default-social-image.png
but a twitter card still doesn't seem to be displaying:
https://twitter.com/CoryMSimon/status/947217511174496256

**Comment by daviddarnes** [comment]
@SimonEnsemble you need to change this image as I think it's way too large and Twitter won't accept it https://simonensemble.github.io/images/OregonCoast.JPG

**Comment by SimonEnsemble** [comment]
Thanks, must've been it. So for others: the following place in `_config.yml` is where you change the default Twitter card, and the file size should not be too large!
```
# 6. Jekyll collections settings                                                            
defaults:                                                                                   
  -                                                                                         
    scope:                                                                                  
      path: ""                                                                              
      type: pages                                                                           
    values:                                                                                 
      layout: page # Default layout                                                         
      image: "../images/treez_light.png" # Default image for sharing                        
  -                                                                                         
    scope:                                                                                  
      path: ""                                                                              
      type: posts                                                                           
    values:                                                                                 
      layout: post # Default layout                                                         
      image: "../images/treez_light.png" # Default image for sharing
```

However oddly I changed the image and the Twitter card is not updating.
